package com.my.newproject2;

public final class C0083R {

    public static final class attr {
    }

    public static final class drawable {
        public static int abcd = C0083R.drawable.abcd;
        public static int abcde = C0083R.drawable.abcde;
        public static int abcq = C0083R.drawable.abcq;
        public static int acad = C0083R.drawable.acad;
        public static int ahah = C0083R.drawable.ahah;
        public static int app_icon = C0083R.drawable.app_icon;
        public static int blueback = C0083R.drawable.blueback;
        public static int bsjjs = C0083R.drawable.bsjjs;
        public static int caf = C0083R.drawable.caf;
        public static int cbnv = C0083R.drawable.cbnv;
        public static int club = C0083R.drawable.club;
        public static int com1 = C0083R.drawable.com1;
        public static int com2 = C0083R.drawable.com2;
        public static int cul = C0083R.drawable.cul;
        public static int cult = C0083R.drawable.cult;
        public static int dadc = C0083R.drawable.dadc;
        public static int dadca = C0083R.drawable.dadca;
        public static int default_image = C0083R.drawable.default_image;
        public static int dfj = C0083R.drawable.dfj;
        public static int dtg = C0083R.drawable.dtg;
        public static int dtga = C0083R.drawable.dtga;
        public static int frie = C0083R.drawable.frie;
        public static int hdjsk = C0083R.drawable.hdjsk;
        public static int help = C0083R.drawable.help;
        public static int helpd = C0083R.drawable.helpd;
        public static int hhhh = C0083R.drawable.hhhh;
        public static int icon3 = C0083R.drawable.icon3;
        public static int ieee = C0083R.drawable.ieee;
        public static int ieeee = C0083R.drawable.ieeee;
        public static int img = C0083R.drawable.img;
        public static int jahs = C0083R.drawable.jahs;
        public static int jjdks = C0083R.drawable.jjdks;
        public static int join = C0083R.drawable.join;
        public static int kkxk = C0083R.drawable.kkxk;
        public static int kskzb = C0083R.drawable.kskzb;
        public static int lang = C0083R.drawable.lang;
        public static int ldknd = C0083R.drawable.ldknd;
        public static int lec = C0083R.drawable.lec;
        public static int lkl = C0083R.drawable.lkl;
        public static int lllla = C0083R.drawable.lllla;
        public static int lllll = C0083R.drawable.lllll;
        public static int nptel = C0083R.drawable.nptel;
        public static int nzjs = C0083R.drawable.nzjs;
        public static int pla = C0083R.drawable.pla;
        public static int pla2 = C0083R.drawable.pla2;
        public static int pla3 = C0083R.drawable.pla3;
        public static int rcc = C0083R.drawable.rcc;
        public static int rci = C0083R.drawable.rci;
        public static int znzn = C0083R.drawable.znzn;
    }

    public static final class id {
        public static int button1 = C0083R.id.button1;
        public static int button2 = C0083R.id.button2;
        public static int button3 = C0083R.id.button3;
        public static int button4 = C0083R.id.button4;
        public static int button5 = C0083R.id.button5;
        public static int button6 = C0083R.id.button6;
        public static int edittext1 = C0083R.id.edittext1;
        public static int edittext2 = C0083R.id.edittext2;
        public static int imageview1 = C0083R.id.imageview1;
        public static int imageview2 = C0083R.id.imageview2;
        public static int imageview3 = C0083R.id.imageview3;
        public static int imageview4 = C0083R.id.imageview4;
        public static int imageview5 = C0083R.id.imageview5;
        public static int imageview6 = C0083R.id.imageview6;
        public static int imageview7 = C0083R.id.imageview7;
        public static int imageview8 = C0083R.id.imageview8;
        public static int imageview9 = C0083R.id.imageview9;
        public static int linear1 = C0083R.id.linear1;
        public static int linear10 = C0083R.id.linear10;
        public static int linear12 = C0083R.id.linear12;
        public static int linear13 = C0083R.id.linear13;
        public static int linear15 = C0083R.id.linear15;
        public static int linear16 = C0083R.id.linear16;
        public static int linear17 = C0083R.id.linear17;
        public static int linear18 = C0083R.id.linear18;
        public static int linear19 = C0083R.id.linear19;
        public static int linear2 = C0083R.id.linear2;
        public static int linear20 = C0083R.id.linear20;
        public static int linear3 = C0083R.id.linear3;
        public static int linear4 = C0083R.id.linear4;
        public static int linear5 = C0083R.id.linear5;
        public static int linear6 = C0083R.id.linear6;
        public static int linear7 = C0083R.id.linear7;
        public static int linear8 = C0083R.id.linear8;
        public static int linear9 = C0083R.id.linear9;
        public static int textview1 = C0083R.id.textview1;
        public static int textview2 = C0083R.id.textview2;
        public static int textview3 = C0083R.id.textview3;
        public static int textview4 = C0083R.id.textview4;
        public static int textview5 = C0083R.id.textview5;
        public static int textview6 = C0083R.id.textview6;
        public static int textview7 = C0083R.id.textview7;
        public static int vscroll1 = C0083R.id.vscroll1;
        public static int webview1 = C0083R.id.webview1;
    }

    public static final class layout {
        public static int acad = C0083R.layout.acad;
        public static int acadact = C0083R.layout.acadact;
        public static int attend = C0083R.layout.attend;
        public static int balan = C0083R.layout.balan;
        public static int book = C0083R.layout.book;
        public static int cafe = C0083R.layout.cafe;
        public static int caffeteria = C0083R.layout.caffeteria;
        public static int calculus = C0083R.layout.calculus;
        public static int cog = C0083R.layout.cog;
        public static int complains = C0083R.layout.complains;
        public static int counsellor = C0083R.layout.counsellor;
        public static int courses = C0083R.layout.courses;
        public static int dadc = C0083R.layout.dadc;
        public static int dcei = C0083R.layout.dcei;
        public static int dceiweb = C0083R.layout.dceiweb;
        public static int dotactivity = C0083R.layout.dotactivity;
        public static int dots = C0083R.layout.dots;
        public static int download = C0083R.layout.download;
        public static int downloadeb = C0083R.layout.downloadeb;
        public static int dtg = C0083R.layout.dtg;
        public static int ecampus = C0083R.layout.ecampus;
        public static int elecebook = C0083R.layout.elecebook;
        public static int exit = C0083R.layout.exit;
        public static int fbl = C0083R.layout.fbl;
        public static int helpdesk = C0083R.layout.helpdesk;
        public static int hostel = C0083R.layout.hostel;
        public static int ieee = C0083R.layout.ieee;
        public static int instl = C0083R.layout.instl;
        public static int internet = C0083R.layout.internet;
        public static int internet1 = C0083R.layout.internet1;
        public static int intranet = C0083R.layout.intranet;
        public static int lect = C0083R.layout.lect;
        public static int main = C0083R.layout.main;
        public static int meet = C0083R.layout.meet;
        public static int mtech = C0083R.layout.mtech;
        public static int mvid = C0083R.layout.mvid;
        public static int new1 = C0083R.layout.new1;
        public static int nptel = C0083R.layout.nptel;
        public static int pivot = C0083R.layout.pivot;
        public static int press = C0083R.layout.press;
        public static int projects = C0083R.layout.projects;
        public static int rcact = C0083R.layout.rcact;
        public static int rccataint = C0083R.layout.rccataint;
        public static int research = C0083R.layout.research;
        public static int sell = C0083R.layout.sell;
        public static int settings = C0083R.layout.settings;
        public static int share = C0083R.layout.share;
        public static int sodality = C0083R.layout.sodality;
        public static int splash = C0083R.layout.splash;
        public static int splo = C0083R.layout.splo;
        public static int usabout = C0083R.layout.usabout;
        public static int webmail = C0083R.layout.webmail;
        public static int weplace = C0083R.layout.weplace;
        public static int wie = C0083R.layout.wie;
        public static int wieieee = C0083R.layout.wieieee;
        public static int youtube = C0083R.layout.youtube;
    }

    public static final class raw {
        public static int tick = C0083R.raw.tick;
    }

    public static final class style {
        public static int AppTheme = C0083R.style.AppTheme;
        public static int FullScreen = C0083R.style.FullScreen;
        public static int NoActionBar = C0083R.style.NoActionBar;
    }
}
